<?php

use Drupal\Core\Database\Database;
use Drupal\Core\Extension\ExtensionList;
use Drupal\Core\Session\AccountProxyInterface;

/**
 * Implements hook_theme().
 */
function ecg_analysis_theme($existing, $type, $theme, $path) {
  // Получаем путь к каталогу модуля через сервис.
  $module_path = \Drupal::service('extension.list.module')->getPath('ecg_analysis');

  return [
    'ecg_report' => [
      'template' => 'ecg-report',                // файл ecg-report.html.twig
      'path' => $module_path . '/templates',     // каталог с шаблоном
      'variables' => [
        'fid' => NULL,
        'file_name' => NULL,
        'summary'   => [],
        'duration'  => 0,
        'duration_s' => NULL,
        'duration_hm' => NULL,
        'fs'        => 0,
        'rr_ms'     => [],
        'total_samples'  => 0,
        'filename' => NULL,
      ],
    ],
  ];
}

/**
 * Helper: register file in index.
 */
function ecg_analysis_index_file(\Drupal\file\FileInterface $file, string $md5): void {
	$uid = \Drupal::currentUser()->id();

  $conn = Database::getConnection();
	$conn->upsert('ecg_raw_index')
		->key('fid')
		->fields([
			'uid'           => (int) $uid,        // НОВОЕ: владелец
			'fid'           => (int) $file->id(),
			'uri'           => $file->getFileUri(),
			'filename'      => $file->getFilename(),
      'size'     => (int) $file->getSize(),
			'md5'           => $md5,
      'created'  => \Drupal::time()->getRequestTime(),
		])
		->execute();
}
